version: '3'

services:
  dfchat:
    image: dfchat:0.2
    container_name: dfchat
    restart: unless-stopped
    # ports:
      # - 8000:8000
    networks:
      - app-network
    volumes:
      - ./database.db:/backend/mydb.db


  dfchat-nginx:
    image: nginx:alpine
    container_name: dfchat-nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - app-network
    volumes:
      - ./nginxconf:/etc/nginx/conf.d
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./dhparam:/etc/ssl/certs
    depends_on:
      - dfchat

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - dfchat-nginx
    command: certonly --webroot --webroot-path=/var/www/html --email youremail@gmail.com --agree-tos --no-eff-email --force-renewal -d yourdomain.com

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./web-root

networks:
  app-network:
    driver: bridge