# Stage 1: Build Vue.js frontend
FROM node:18 AS builder
WORKDIR /app

# Install dependencies
COPY vue-chat-gui/package*.json ./
# `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync.
# RUN npm ci
RUN npm install

# Build the Vue.js app
COPY vue-chat-gui/ ./
RUN npm run build

# Stage 2: Setup the FastAPI backend
FROM python:3.10
WORKDIR /backend

# Install dependencies
COPY backend/requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir uvicorn[standard]
# Copy the Vue.js app from the previous stage

# Add the FastAPI app
COPY backend/ ./

# Copy the Vue.js app from the previous stage
COPY --from=builder /app/dist/ /backend/static/

# Run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

